@echo off
echo Starting FastAPI Backend...
start cmd /k "cd backend && venv\Scripts\activate && uvicorn main:app --reload --port 8000"
echo Starting Vite Frontend...
start cmd /k "cd frontend && npm run dev"
